server:
  port: 8200
  servlet:
    context-path: /proxy
spring:
  cloud:
    gateway:
      routes:
        - id: app_route
          uri: http://localhost:8100/app
          predicates:
            - Path=/proxy/app/**
          filters:
            - StripPrefix=1
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE